id: I3924C3FA
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T14:12:14+00:00'
last_modified: '2022-06-09T06:24:57.012637+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG6135
  title: འཛམ་གླིང་དེང་རབས་ལོ་རྒྱུས་ཀྱི་གཏམ་རྒྱུད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    0E37:
      image_group_id: I1KG8437
      title: Volume 1 of 'dzam gling deng rabs lo rgyus kyi gtam rgyud/
      total_pages: 354
      order: 1
      base_file: 0E37.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
