id: P007837
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG6135
  title: འཛམ་གླིང་དེང་རབས་ལོ་རྒྱུས་ཀྱི་གཏམ་རྒྱུད།
  author: ''
  volumes:
    43cf0621afde48609831d8ec21da2b7c:
      image_group_id: I1KG8437
      title: ''
      volume_number: 1
      total_pages: 354
ebook_metadata:
  title: འཛམ་གླིང་དེང་རབས་ལོ་རྒྱུས་ཀྱི་གཏམ་རྒྱུད།
  author: ''
  sku: P007837
  cover: cover.jpg
  layers:
  - pagination
