id: P007837
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG6135
  title: འཛམ་གླིང་དེང་རབས་ལོ་རྒྱུས་ཀྱི་གཏམ་རྒྱུད།
  author: ''
  volumes:
    c40c686911b144879f477758ad0aa949:
      image_group_id: I1KG8437
      title: Volume 1 of 'dzam gling deng rabs lo rgyus kyi gtam rgyud/
      volume_number: 1
      total_pages: 354
      base_file: v001.txt
